### ISSUE TITLE
Do we need contact persons for sections?

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#102]
Right now we have contacts for whole projects, as well as for excavations full implemented.

But within the `SectionForm` there is currently a placeholder tab-item for `DocContacts` as well. 

So the question: **Do we really need dedicated contacts for each section, or can we remove that?**

**Comment by Me0li** [comment]
I think that's a question for our archaeologists. I implemented it as an offer to keep the possibility open. If we don't need it, we can simply remove it
