### ISSUE TITLE
How to implement Color Picker in Munsell Color space

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#103]
The current vuetify color-picker only supports `['rgb', 'rgba', 'hsl', 'hsla', 'hex', 'hexa']`
See: https://vuetifyjs.com/en/api/v-color-picker/#props-modes

According to existing documents from the archeologists they need the colors in Munsell Color space (HVC -> Hue, Value, Chroma)
See: https://en.wikipedia.org/wiki/Munsell_color_system

We could just **convert RGB values to the HVC** color space, but this comes with inaccuracies.

Alternatively, we could **implement our own color picker**, similar to: https://github.com/pteromys/munsell

Third option could be to just not offer a color picker and **just give three text inputs** for the HVC values.

![chrome_FqNCOg6h2G](https://user-images.githubusercontent.com/15029310/236634775-14c8c438-2a2d-407f-94a2-d0a72fac0d4b.png)

**Comment by Me0li** [comment]
I saw this issue and would like to talk to you about it in person. I have some questions before I can propose a solution

**Comment by JuHardtung** [comment]
Now we can implement a [Munsell-Color Space](https://munsell.com/about-munsell-color/how-color-notation-works/how-to-read-color-chart/) Input module. This would have three attribute fields to describe a full color.

Example Munsell-Color: **5R 7/2**

- **5R** is the Hue (or color)
- **7** is the Value (or lightness/darkness)
- **2** is the Chroma (weak/strong)
