### ISSUE TITLE
Can‘t use texture data in code 

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-2-#104]
Data from backend is not useable, when applied to a material. Maybe a conversion to base64 before upload will fix the problem?

**Comment by JuHardtung** [comment]
Firebase storage expects full files so i don't know how i could encode an image to base64 and then still upload it. I could maybe encode it with [btoa()](https://developer.mozilla.org/en-US/docs/Web/API/btoa), save that to a .txt file and then upload it?

But either way, we have to encode it to base64 and you should be able to that in the frontend. The only issue there seems to be that the [btoa()](https://developer.mozilla.org/en-US/docs/Web/API/btoa)-function expects every character to only occupy one byte. So when we have an image, which contains characters larger than a byte, then btoa() will fail.


Similar issue: 
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings

And relevant documentation: [base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64)

**Comment by TMink** [comment]
For now the "FileReader"-class does the job. It takes a file or a blob and converts it from utf-8 into base64. This string can then be transferred to IndexedDB. 

With this its at least possible to push on development, but the problem the firebase problem still persists.
