### ISSUE TITLE
backend is crashing after i try to access excavations in the navigation bar

### ISSUE THREAD

**Issue by robertklaus** [TMink/Digitales-3D-Feldbuch-Projekt-2-#105]
After the latest update I get following error message in git bash. 
![image](https://user-images.githubusercontent.com/44345307/236673676-78f6a3e2-4f79-47bf-8b22-0422b7602c90.png)

That is what i see in the frontend for excavations and if you check the picture you will see the rest besides "Projekt" aren't showing correctly either.
![probelm](https://user-images.githubusercontent.com/44345307/236673931-3bab0729-d9b5-4326-82ea-8d85b286d935.png)

Does someone know this problem and can help me?

**Comment by JuHardtung** [comment]
Firstly, check the browser console with F12 to get the detailed error message.

Secondly, which project do you have selected? It might be, that you have a project selected, which has no excavations connected to it. This in turn would probably return an error, because the backend expects an array with the excavation ids.

**Comment by robertklaus** [comment]
> Secondly, which project do you have selected? It might be, that you have a project selected, which has no excavations connected to it. This in turn would probably return an error, because the backend expects an array with the excavation ids.

You absolutely correct, i selected a project which isn't connected to an excavation yet. I will create more data sets in firebase so every project has an excavation. Thanks for you fast reply. 

I will close the issue.

**Comment by JuHardtung** [comment]
This should be fixed by adding extra checks, if the list is empty or undefined. Similar behavior happens in DocColors, DocArtifacts, DocContacts, DocDates, DocExcavations, FeaturesOverview, ArtifactsOverview, ExcavationsOverview
