### ISSUE TITLE
Backend Crash when trying to add a new contact

### ISSUE THREAD

**Issue by Me0li** [TMink/Digitales-3D-Feldbuch-Projekt-2-#106]
When I want to add a new contact on the project page, the backend crashes.

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/32168571/d4aaa10b-23dd-4fad-9a15-8c8f266225ca)

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/32168571/1747646d-7b41-44b4-8e81-920bacb4c74a)

**Comment by JuHardtung** [comment]
Had the project already some contacts, or was the initial list empty so far?
