### ISSUE TITLE
Reduction of 3d model filesize (.obj ~ 300)

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-2-#109]
Found an interesting post, that suggests the conversion from .obj to .gltf, but server side. I dont know if this will be problemetic in terms of textures.

Three.js Post: https://discourse.threejs.org/t/how-to-convert-obj-fbx-to-gltf-before-loading-to-scene/10953

Library: https://github.com/CesiumGS/obj2gltf

**Comment by JuHardtung** [comment]
Now using [.glb](https://docs.fileformat.com/3d/glb/) format, which is the binary form of [.gltf](https://docs.fileformat.com/3d/gltf/) (GL Transmission Format). GLB includes all data (model, texture and material) within one file and is much smaller compared to [.obj](https://docs.fileformat.com/3d/obj/), which saves the data as plain text.
