### ISSUE TITLE
Problem with post-method (add_length) at DocLengths

### ISSUE THREAD

**Issue by robertklaus** [TMink/Digitales-3D-Feldbuch-Projekt-2-#110]
I have a problem with "post" at DocLenghts. This following error message is displayed in my console:
![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/44345307/b03756b7-5026-4869-84ff-9eda40f7cec9)

I already checked the addLenght method multiple times but i can't find any mistakes.
If anyone have the time to check the problem out, it would be a blessing.

**Comment by JuHardtung** [comment]
There should be another error in the console where you startet the Backend Server. Can you send that?

**Comment by robertklaus** [comment]
The console shows following status codes:
![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/44345307/bf9689b0-47d1-4166-99fe-0d74e446b401)

**Comment by JuHardtung** [comment]
From the Backend Log I can tell that the earlier GET request '/artifacts/undefined' had a missing ID. So probably this ID is still missing when you are trying to create a new Length for this specific artifact.

Should be an easy fix to just follow were the ID is missing or not given
