### ISSUE TITLE
Problem with ThreeJS build-in function for clipping

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-2-#111]
For the realisation of tools like Segmentation/Extraction, we need a function, that can crop/clip segments of the mesh. ThreeJS provides the 'stencil-clipping' method as an example.

Problem is, that this method operates with a three.plane ([https://threejs.org/docs/#api/en/math/Plane](url)) rather than a three.planegeometry ([https://threejs.org/docs/#api/en/geometries/PlaneGeometry](url)). The three.plane is tow dimensional surface that extends infinitly in 3d space, represented in Hessian normal form and will not behave like a normal 3D-Object when transformed.

When manipulating the unit normal vector, the clipping output will be distorted: 
<img width="895" alt="image" src="https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/15029632/06c7ed3c-b76a-42cd-81d3-0cb0d4188e95">

This limits the usability of the function. Maybe we can find another solution to this Problem with a different library that works with ThreeJS.

**Comment by TMink** [comment]
Possible solutions can be ...

BVH - [https://www.npmjs.com/package/three-mesh-bvh](url)
... and ...
BVH-CSG - [https://www.npmjs.com/package/three-bvh-csg](url)

Both libraries offer a variety of function like bool operations, or shaping/painting meshes.
But on an attempt of importing BVH i get following error: 
<img width="503" alt="rest_operator" src="https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/15029632/6f892323-6fac-409c-acc8-b245f7c7aed6">

**Comment by TMink** [comment]
The unexpected token was the "spread operator" ( '...' ). It seems like bable got a problem with it.

Next week i will try to find a possible solution. Seems like the problem is already present in different projects:

Examples:
- [https://stackoverflow.com/questions/56003497/nodejs-problem-with-spread-operators-unexprected-token](url)
- [https://stackoverflow.com/questions/65875841/javascript-and-spread-operator-as-unexpected-token](url)

**Comment by JuHardtung** [comment]
Fixed after an upgrade of the whole project to Vue3 with Vite
