### ISSUE TITLE
Alternative Browser Tab Favicon

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#114]
We need an alternative browser tab favicon. Currently we still show the default Vue.js logo (see below). 

So what favicon should we use and should we show this icon at other places within the webapp as well?

![chrome_mItJnCGmRy](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/15029310/68edd558-5bc7-49ec-885c-f3ae9a55abf1)

**Comment by Me0li** [comment]
One possibility would be to create an official logo for our system. Alternatively, I would try to use the TH Köln logo first

**Comment by JuHardtung** [comment]
Yes, an official logo would be best

**Comment by Me0li** [comment]
Then i'll try to come up with something

**Comment by Me0li** [comment]
What do you think about this little icon?

![3DDF_Logo](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/32168571/5a8508e8-2155-4010-85a8-f90dbf3e5661)

**Comment by JuHardtung** [comment]
I like the first one, but in the browser you can't really see the details on the book, as the favicon is only displayed at 16x16px.
