### ISSUE TITLE
integrate feedback system into the system?

### ISSUE THREAD

**Issue by Me0li** [TMink/Digitales-3D-Feldbuch-Projekt-2-#116]
What do you think of a possibility to enter feedback directly into the system? The user himself does not have to be able to see it, only we as admins need access. In case of doubt, someone could use the system without our presence and use the system without our input and still report bugs/feedback

**Comment by JuHardtung** [comment]
Do you mean something like a 'Report Bug' Button for users? Such reports could be automatically sent to the backend, where we can check them out at a later point.

**Comment by Me0li** [comment]
yes something like that

**Comment by JuHardtung** [comment]
Turned out not to be needed, as we got immediate feedback while the archeologists used the system.

Although this could still be a useful feature once the system has been deployed to actual users.
