### ISSUE TITLE
Should the content be divided into two seperate areas?

### ISSUE THREAD

**Issue by Me0li** [TMink/Digitales-3D-Feldbuch-Projekt-2-#117]
Fields such as "Planum" and "Editor" are currently combined in a V-Card although they are not directly related. Should these areas be separated or is that negligible?

![image](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/32168571/01c11e37-c8a8-4df1-a5bf-bbd529fcf0c6)

**Comment by JuHardtung** [comment]
I think we should separate them, as their data is not directly connected to each other (like the Gauss-Krüger-coordinates).

**Comment by Me0li** [comment]
Ok I will do that
