### ISSUE TITLE
We don't have the English phrase lists for Materials, Titles and Datings

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#120]
We currently only have these lists in German, but would need the translations for our English version as well.
So either we translate them by hand, find the translated lists somewhere on the internet, or we translate the lists with Google Translate/ChatGPT and hope for the best.

![NVIDIA_Share_D0WUZnmNPu](https://github.com/TMink/Digitales-3D-Feldbuch-Projekt-2-/assets/15029310/cd092aa0-3818-4cf9-b58b-8b25a35741e4)

**Comment by Me0li** [comment]
Since the lists are very long, I would suggest translating with chatGPT and then cleaning up errors on the excavation

**Comment by JuHardtung** [comment]
The archeologists didn't want or use these phrase lists, so this issue can be closed for now. We can revisit this topic once we specifically develop for the APX.
