### ISSUE TITLE
Welche Daten sollen im Reiter „Proben“ angegeben werden? (3D-Modelle?)

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-2-#3]

**Comment by JuHardtung** [comment]
Now using the [Stellenkartensystem](https://file.notion.so/f/s/8b2c6543-bcc1-4b40-8ce2-8196a0b1644b/Grabungsrichtlinien_2020.pdf?id=e8a55b47-6a93-44c5-a73b-7c27c3ce3534&table=block&spaceId=4e3c389b-6012-48c4-ad1c-92253d68fe60&expirationTimestamp=1687683493648&signature=wZQhUIcl4NXolOKLM0Ctc1Pj8jFmDGgx-x7mrxSGB-U&downloadName=Grabungsrichtlinien_2020.pdf), which does not have a dedicated 'Proben' section.
