### ISSUE TITLE
Navbar Button of the currently opened page should be deactivated

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#90]
Currently you can click on the button for a page that is already opened, which results in an error.

Example error when clicking on the "Projekt" button while on the "ProjectsOverview" page:
`Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/projects".`

Either create a check when clicking on a button, so it doesn't try to redirect, or just deactivate it.

**Comment by Me0li** [comment]
I've noticed this error too. I would like it if the current page button was just greyed out
