### ISSUE TITLE
Sidebar automatically opens unwanted

### ISSUE THREAD

**Issue by JuHardtung** [TMink/Digitales-3D-Feldbuch-Projekt-2-#92]
After opening the Sidebar once and then switching pages the Sidebar keeps opening automatically. 

The Issue happens on Chrome for me.

Browser console throws this warning:
![chrome_o0Gg8R2ehV](https://user-images.githubusercontent.com/15029310/233676722-3646f66c-2302-4a01-8aca-224e7d71c5df.png)

**Comment by Me0li** [comment]
UPDATE 27.04. - I have the same problem now, unfortunately I have no idea why

**Comment by Me0li** [comment]
I found a possible reason for this problem. If I open the page in full screen, then this problem does not occur. When I open the page in a small window it occurs again

**Comment by robertklaus** [comment]
> I found a possible reason for this problem. If I open the page in full screen, then this problem does not occur. When I open the page in a small window it occurs again

That's correct, i could recreate the problem in a small window. I will research for a solution and keep you guys updated.
