### ISSUE TITLE
Cant update empty store, when initialized

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-2-#93]
When trying to update the array-content in code, right after creating an empty  store

![image](https://user-images.githubusercontent.com/15029632/233678314-beafcf25-d255-4f50-9d37-ea331f9070f2.png)

**Comment by JuHardtung** [comment]
Does this issue still persist? If so, what is contained in this array-content, and where are you trying to change it?

**Comment by TMink** [comment]
Not anymore. Problem was the async communication, wich lead to a wrong sequence of requests.
