### ISSUE TITLE
"Currently Selected" Button

### ISSUE THREAD

**Issue by Me0li** [TMink/Digitales-3D-Feldbuch-Projekt-2-#98]
When I have selected a project, a "Currently selected" button appears for this project. If I select a different project, this button does not switch to the new project

**Comment by JuHardtung** [comment]
I can't reproduce the issue, even when deleting cookies in between actions.

**Comment by Me0li** [comment]
I found the mistake. A selected project is always placed at the top of the list. I had mistakenly assumed that the "currently selected" button jumps to the position of the selected project.
